//This file is to make it easy to view all of the weather icons as a set.
//The icons designed for release with syncWXremix are Ctrl-A encoded ASCII (.ASC) files for maximum compatibility.
//Feel free to make your own icons as replacements, but if you base the ASCII artwork off of the included icon set or
//still use part of the included icon set, then you must include the "License" file included in the icon folder with
//any distributions of your icon set, as the icon pack I designed was based on/inspired by wego - https://github.com/schachmat/wego

//Set this file up as a javascript door in Synchronet, and it will cycle through the icon set 
//located in <drive>:\sbbs\text\menu\weather (or <root>/sbbs/text/menu/weather/) if you choose to use the bbs.menu option.
//If you do use the bbs.menu option in weather.js, it will load up files with the same hierarchy of the SBBS menu. 
//Here is the section from the old http://synchro.net/docs page
//ANS     Contains ANSI escape sequences suitable for color display
//MON     Contains ANSI escape sequences suitable for monochrome display
//ASC     Contains no ANSI
//All of the above file types can contain ctrl-a codes, and only the ASC file
//must exist. If a user has color ANSI, the ANS file will be displayed; if it
//doesn't exist the ASC file will be displayed. If a user has monochrome ANSI,
//the MON file will be displayed; if it doesn't exist the ANS file will be
//displayed; and if it doesn't exist the ASC file is then displayed.
//A user without ANSI will always be displayed the ASC file.

//Weather Icon designs done in Ctrl-A colored ASCII (Synchronet Formatting) by KenDB3 - http://bbs.kd3.us 
//Weather Icons inspired by wego (Weather Client for Terminals), created by Markus Teich - https://github.com/schachmat/wego


load("http.js");
load("sbbsdefs.js");

function viewweathericons() {
		var wh = "\001w\1h"; //Synchronet Ctrl-A Code for High Intensity White
		console.clear();
		console.crlf();
		console.putmsg(wh + "chanceflurries");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/chanceflurries");
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_chanceflurries");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/nt_chanceflurries");
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "chancerain");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/chancerain");
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_chancerain");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/nt_chancerain");
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "chancesleet");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/chancesleet");
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_chancesleet");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/nt_chancesleet");
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "chancesnow");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/chancesnow");
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_chancesnow");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/nt_chancesnow");
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "chancetstorms");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/chancetstorms");
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_chancetstorms");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/nt_chancetstorms");
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "clear");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/clear");
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_clear");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/nt_clear");
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "cloudy");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/cloudy");
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_cloudy");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/nt_cloudy");
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "flurries");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/flurries");
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_flurries");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/nt_flurries");
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "fog");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/fog");
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_fog");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/nt_fog");
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "hazy");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/hazy");
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_hazy");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/nt_hazy");
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "mostlycloudy");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/mostlycloudy");
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_mostlycloudy");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/nt_mostlycloudy");
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "mostlysunny");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/mostlysunny");
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_mostlysunny");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/nt_mostlysunny");
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "partlycloudy");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/partlycloudy");
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_partlycloudy");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/nt_partlycloudy");
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "partlysunny");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/partlysunny");
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_partlysunny");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/nt_partlysunny");
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "rain");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/rain");
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_rain");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/nt_rain");
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "sleet");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/sleet");
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_sleet");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/nt_sleet");
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "snow");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/snow");
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_snow");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/nt_snow");
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "sunny");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/sunny");
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_sunny");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/nt_sunny");
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "tstorms");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/tstorms");
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_tstorms");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/nt_tstorms");
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "unknown");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		bbs.menu("weather/unknown");
		console.crlf();
		console.crlf();
		console.putmsg(wh + "The unknown icon is a catch-all in case there is no icon found.");
		console.crlf();
		console.putmsg(wh + "If you see it, then you are missing an icon, Wunderground is using a new icon,");
		console.crlf();
		console.putmsg(wh + "or the weather data is simply incomplete for that particular query.");
		console.crlf();console.crlf();
		console.pause();
    }
		
viewweathericons();
console.clear();
