//This file is to make it easy to view all of the weather icons as a set.
//The icons designed for release with syncWXremix are Ctrl-A encoded ASCII (.ASC) files for maximum compatibility.
//Feel free to make your own icons as replacements, but if you base the ASCII artwork off of the included icon set or
//still use part of the included icon set, then you must include the "License" file included in the icon folder with
//any distributions of your icon set, as the icon pack I designed was based on/inspired by wego - https://github.com/schachmat/wego

//Weather Icon designs done in Ctrl-A colored ASCII (Synchronet Formatting) by KenDB3 - http://bbs.kd3.us 
//Weather Icons inspired by wego (Weather Client for Terminals), created by Markus Teich - https://github.com/schachmat/wego

load("http.js");
load("sbbsdefs.js");
var opts=load({},"modopts.js","SyncWX"); 

//File extension for the weather icons (Ex: .asc, .ans, .mon, .rip) is now defined in /sbbs/ctrl/modopts.ini
//You can change it there (see sysop.txt) or hard code it into this file for testing (ex: var weathericon_ext = ".asc";)
var weathericon_ext = opts.weathericon_ext; 

function viewweathericons() {
		var wh = "\001w\1h"; //Synchronet Ctrl-A Code for High Intensity White
		console.clear();
		console.crlf();
		console.putmsg(wh + "chanceflurries");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/chanceflurries" + weathericon_ext);
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_chanceflurries");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/nt_chanceflurries" + weathericon_ext);
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "chancerain");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/chancerain" + weathericon_ext);
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_chancerain");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/nt_chancerain" + weathericon_ext);
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "chancesleet");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/chancesleet" + weathericon_ext);
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_chancesleet");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/nt_chancesleet" + weathericon_ext);
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "chancesnow");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/chancesnow" + weathericon_ext);
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_chancesnow");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/nt_chancesnow" + weathericon_ext);
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "chancetstorms");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/chancetstorms" + weathericon_ext);
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_chancetstorms");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/nt_chancetstorms" + weathericon_ext);
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "clear");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/clear" + weathericon_ext);
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_clear");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/nt_clear" + weathericon_ext);
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "cloudy");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/cloudy" + weathericon_ext);
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_cloudy");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/nt_cloudy" + weathericon_ext);
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "flurries");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/flurries" + weathericon_ext);
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_flurries");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/nt_flurries" + weathericon_ext);
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "fog");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/fog" + weathericon_ext);
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_fog");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/nt_fog" + weathericon_ext);
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "hazy");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/hazy" + weathericon_ext);
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_hazy");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/nt_hazy" + weathericon_ext);
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "mostlycloudy");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/mostlycloudy" + weathericon_ext);
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_mostlycloudy");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/nt_mostlycloudy" + weathericon_ext);
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "mostlysunny");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/mostlysunny" + weathericon_ext);
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_mostlysunny");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/nt_mostlysunny" + weathericon_ext);
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "partlycloudy");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/partlycloudy" + weathericon_ext);
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_partlycloudy");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/nt_partlycloudy" + weathericon_ext);
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "partlysunny");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/partlysunny" + weathericon_ext);
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_partlysunny");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/nt_partlysunny" + weathericon_ext);
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "rain");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/rain" + weathericon_ext);
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_rain");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/nt_rain" + weathericon_ext);
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "sleet");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/sleet" + weathericon_ext);
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_sleet");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/nt_sleet" + weathericon_ext);
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "snow");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/snow" + weathericon_ext);
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_snow");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/nt_snow" + weathericon_ext);
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "sunny");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/sunny" + weathericon_ext);
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_sunny");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/nt_sunny" + weathericon_ext);
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "tstorms");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/tstorms" + weathericon_ext);
		console.crlf();console.crlf();console.crlf();
		console.putmsg(wh + "nt_tstorms");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/nt_tstorms" + weathericon_ext);
		console.crlf();
		console.pause();
		console.clear();
		console.crlf();
		console.putmsg(wh + "unknown");
		console.crlf();
		console.putmsg(wh + "--------------------");
		console.crlf();
		console.printfile(js.exec_dir + "icons/unknown" + weathericon_ext);
		console.crlf();
		console.crlf();
		console.putmsg(wh + "The unknown icon is a catch-all in case there is no icon found.");
		console.crlf();
		console.putmsg(wh + "If you see it, then you are missing an icon, Wunderground is using a new icon,");
		console.crlf();
		console.putmsg(wh + "or the weather data is simply incomplete for that particular query.");
		console.crlf();console.crlf();
		console.pause();
    }
		
viewweathericons();
console.clear();
console.aborted = false;
exit();
